apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./observability
  - ./production-namespace.yaml
  - ./address-validation-service
  - ./billing-service
  - ./customer-service
  - ./delivery-service
